version: '3.3'
services: 
 eureka-server:
  build : ./eurekaserver/eurekaserver
  ports :
    - 8761:8761
  networks:
    - microservices-network
 auth-service:
  build: ./authservice/authservice
  ports:
    - 4444:4444
  networks:
    - microservices-network
  depends_on:
    - eureka-server
 gatewy-service:
  build: ./gateway/gateway
  ports:
    - 2222:2222
  depends_on:
    - eureka-server
    - auth-service
  networks:
    - microservices-network
networks:
  microservices-network:
   driver : bridge